### ISSUE TITLE
*** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by TuMePJlaH** [continental/rmw_ecal#22] opened 2021-09-07 08:29 UTC
ros2 foxy
cmake version 3.16.3
```bash
sudo add-apt-repository ppa:ecal/ecal-latest
sudo apt-get update
sudo apt-get install ecal
mkdir ~/ws/src -p
cd ~/ws/src
source /opt/ros/foxy/setup.bash
git clone https://github.com/continental/rosidl_typesupport_protobuf.git
git clone https://github.com/continental/rmw_ecal.git
cd ~/ws
colcon build
```

![image](https://user-images.githubusercontent.com/17141754/132309696-3021991f-91b6-4208-984a-1c88cd5c50c1.png)

What am I doing wrong?

**Comment by brakmic-aleksandar** [comment] 2021-09-22 16:05
Wierd, i can't seem to b able to reproduce it, do you mind sharing problematic build.make file with me?

**Comment by TuMePJlaH** [comment] 2021-10-04 07:05
[build.make.txt](https://github.com/continental/rmw_ecal/files/7276012/build.make.txt)

**Comment by brakmic-aleksandar** [comment] 2022-02-01 12:47
Closing this because i couldn't reproduce it.

**Closed by brakmic-aleksandar** 2022-02-01 12:47 UTC

**Comment by adityasivarajmz** [comment] 2023-02-20 05:58
I am facing the exact same issue too. Please look into this.
